#!/usr/bin/env bash
set -e
test -n "${SBTENV_DEBUG}" && set -x

program="${0##*/}"
if [ "${program}" = "sbt" ]; then
  for arg; do
    case "${arg}" in
      -- ) break ;;
    */* )
      if [ -f "${arg}" ]; then
        export SBTENV_DIR="${arg%/*}"
        break
      fi
      ;;
  esac
done
fi

export SBTENV_ROOT="/Users/mazgi/.sbtenv"
exec "/Users/mazgi/.sbtenv/libexec/sbtenv" exec "${program}" "${@}"
