#!/usr/bin/env bash
# Summary: Display the version of sbtenv
#
# Displays the version number of this sbtenv release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.

set -e
test -n "${SBTENV_DEBUG}" && set -x

version="0.0.8"

if cd "${SBTENV_ROOT}" 2> /dev/null; then
  git_revision="$(git describe --tags HEAD 2> /dev/null || true)"
  git_revision="${git_revision#version/}"
fi

echo "sbtenv ${git_revision:-${version}}"

