#!/usr/bin/env bash
# Summary: Explain how the current sbt version is set

set -e
test -n "${SBTENV_DEBUG}" && set -x

if [ -n "${SBTENV_VERSION}" ]; then
  echo "SBTENV_VERSION environment variable"
else
  version="$(sbtenv-version-project)"
  if [ -z "${version}" ]; then
    version="$(sbtenv-version-file)"
  fi
  echo "${version}"
fi

