#!/usr/bin/env bash
# Summary: Show the current sbt version and its origin
#
# Shows the currently selected sbt Version and how it was
# selected. To obtain only the version string, use `sbtenv
# version-name`.

set -e
test -n "${SBTENV_DEBUG}" && set -x

echo "$(sbtenv-version-name) (set by $(sbtenv-version-origin))"

